/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author karol
 */
public class FrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemCategoria = new javax.swing.JMenuItem();
        itemCartao = new javax.swing.JMenuItem();
        itemCidade = new javax.swing.JMenuItem();
        itemConta = new javax.swing.JMenuItem();
        itemEpisodio = new javax.swing.JMenuItem();
        itemFilme = new javax.swing.JMenuItem();
        itemPlano = new javax.swing.JMenuItem();
        itemProdutora = new javax.swing.JMenuItem();
        itemSerie = new javax.swing.JMenuItem();
        itemTemporada = new javax.swing.JMenuItem();
        itemUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Arquivos");

        itemCategoria.setText("Categoria");
        itemCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(itemCategoria);

        itemCartao.setText("Cartão");
        itemCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCartaoActionPerformed(evt);
            }
        });
        jMenu1.add(itemCartao);

        itemCidade.setText("Cidade");
        itemCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCidadeActionPerformed(evt);
            }
        });
        jMenu1.add(itemCidade);

        itemConta.setText("Conta");
        itemConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemContaActionPerformed(evt);
            }
        });
        jMenu1.add(itemConta);

        itemEpisodio.setText("Episodio");
        itemEpisodio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEpisodioActionPerformed(evt);
            }
        });
        jMenu1.add(itemEpisodio);

        itemFilme.setText("Filme");
        itemFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFilmeActionPerformed(evt);
            }
        });
        jMenu1.add(itemFilme);

        itemPlano.setText("Plano");
        itemPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPlanoActionPerformed(evt);
            }
        });
        jMenu1.add(itemPlano);

        itemProdutora.setText("Produtora");
        itemProdutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProdutoraActionPerformed(evt);
            }
        });
        jMenu1.add(itemProdutora);

        itemSerie.setText("Serie");
        itemSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSerieActionPerformed(evt);
            }
        });
        jMenu1.add(itemSerie);

        itemTemporada.setText("Temporada");
        itemTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTemporadaActionPerformed(evt);
            }
        });
        jMenu1.add(itemTemporada);

        itemUsuario.setText("Usuario");
        itemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(itemUsuario);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTemporadaActionPerformed
        // TODO add your handling code here:
        new DialogTemporada(this, true).setVisible(true);
    }//GEN-LAST:event_itemTemporadaActionPerformed

    private void itemCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoriaActionPerformed
        // TODO add your handling code here:
        new DialogCategoria(this, true).setVisible(true);
    }//GEN-LAST:event_itemCategoriaActionPerformed

    private void itemCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCartaoActionPerformed
        // TODO add your handling code here:
        new DialogCartao(this, true).setVisible(true);
    }//GEN-LAST:event_itemCartaoActionPerformed

    private void itemCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCidadeActionPerformed
        // TODO add your handling code here:
        new DialogCidade(this, true).setVisible(true);
    }//GEN-LAST:event_itemCidadeActionPerformed

    private void itemContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemContaActionPerformed
        // TODO add your handling code here:
        new DialogConta(this, true).setVisible(true);
    }//GEN-LAST:event_itemContaActionPerformed

    private void itemEpisodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEpisodioActionPerformed
        // TODO add your handling code here:
        new DialogEpisodio(this, true).setVisible(true);
    }//GEN-LAST:event_itemEpisodioActionPerformed

    private void itemFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFilmeActionPerformed
        // TODO add your handling code here:
        new DialogFilme(this, true).setVisible(true);
    }//GEN-LAST:event_itemFilmeActionPerformed

    private void itemPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPlanoActionPerformed
        // TODO add your handling code here:
        new DialogPlano(this, true).setVisible(true);
    }//GEN-LAST:event_itemPlanoActionPerformed

    private void itemProdutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProdutoraActionPerformed
        // TODO add your handling code here:
        new DialogProdutora(this, true).setVisible(true);
    }//GEN-LAST:event_itemProdutoraActionPerformed

    private void itemSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSerieActionPerformed
        // TODO add your handling code here:
        new DialogSerie(this, true).setVisible(true);
    }//GEN-LAST:event_itemSerieActionPerformed

    private void itemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioActionPerformed
        // TODO add your handling code here:
        new DialogUsuario(this, true).setVisible(true); 
    }//GEN-LAST:event_itemUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCartao;
    private javax.swing.JMenuItem itemCategoria;
    private javax.swing.JMenuItem itemCidade;
    private javax.swing.JMenuItem itemConta;
    private javax.swing.JMenuItem itemEpisodio;
    private javax.swing.JMenuItem itemFilme;
    private javax.swing.JMenuItem itemPlano;
    private javax.swing.JMenuItem itemProdutora;
    private javax.swing.JMenuItem itemSerie;
    private javax.swing.JMenuItem itemTemporada;
    private javax.swing.JMenuItem itemUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
